language: go

go:
  - 1.13.x

go_import_path: github.com/mitjaziv/statik

install:
  - go build -v
  - ./statik -f -src=./example/public -dest=./example/ -include="*.jpg,*.txt,*.html,*.css,*.js"

script:
  - go test -v -bench=. ./...
